services:
  frontend:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - /opt/app/node_modules
      - .:/opt/app
    networks:
      - frontend_some-net
networks:
  frontend_some-net:
    external: true
